import type { ComparisonResult, MortgageInput, PrepaymentMode } from '../../core/mortgage/types';
import type { AutoScenarioSettings } from '../../core/mortgage/scenarioInsights';
import { findBestPrepaymentMonth } from '../../core/mortgage/scenarioInsights';
import { calculatePrepaymentEffects } from '../../core/mortgage/prepaymentEffects';
import { formatMoney } from '../../shared/formatMoney';
import { MoneyInput } from '../../shared/ui/MoneyInput';

const modeLabel = (mode: PrepaymentMode) => (mode === 'reduceTerm' ? 'уменьшение срока' : 'уменьшение платежа');
const durationText = (months: number) => months >= 12 ? `${Math.floor(months / 12)} г. ${months % 12} мес.` : `${months} мес.`;

export function ResultSummary({ result, input, autoScenario, setAutoScenario }: { result: ComparisonResult; input: MortgageInput; autoScenario: AutoScenarioSettings; setAutoScenario: (next: AutoScenarioSettings) => void }) {
  const active = result.withPrepayments;
  const firstYear = active.schedule.slice(0, 12);
  const firstYearInterest = firstYear.reduce((acc, row) => acc + row.interest, 0);
  const firstYearPrincipal = firstYear.reduce((acc, row) => acc + row.principal, 0);
  const breakPoint = active.schedule.find((row) => row.principal > row.interest);
  const bankShare = active.summary.totalPayment > 0 ? (active.summary.totalInterest / active.summary.totalPayment) * 100 : 0;
  const hasPrepayments = input.prepayments.some((p) => p.amount > 0);
  const bestPayment = findBestPrepaymentMonth(active.schedule);
  const averageMonthlyInsurance = active.schedule.length > 0 ? active.summary.totalInsuranceCost / active.schedule.length : 0;
  const monthlyObligation = (active.monthlyPayment ?? active.schedule[0]?.payment ?? 0) + averageMonthlyInsurance;
  const recommendedIncomeComfort = monthlyObligation / 0.3;
  const recommendedIncomeTense = monthlyObligation / 0.4;
  const incomeRatio = input.incomeMonthly && input.incomeMonthly > 0 ? monthlyObligation / input.incomeMonthly : undefined;
  const incomeZone = incomeRatio === undefined ? '' : incomeRatio <= 0.3 ? 'зелёная' : incomeRatio <= 0.4 ? 'жёлтая' : incomeRatio <= 0.5 ? 'оранжевая' : 'красная';
  const bankApartmentEquivalent = input.propertyPrice > 0 ? active.summary.totalInterest / input.propertyPrice : 0;
  const savedApartmentEquivalent = input.propertyPrice > 0 ? result.interestSavings / input.propertyPrice : 0;
  const effects = calculatePrepaymentEffects(input);
  const progress = Math.min(100, result.interestSavings > 0 ? (result.interestSavings / Math.max(1, result.baseline.summary.totalInterest)) * 100 : 0);

  return <>
    <div className="panel section"><h3>Центр 2. Что получилось</h3><div className="cards kpi-grid"><div className="card"><h4>Сумма кредита</h4><p>{formatMoney(input.loanAmount)}</p></div><div className="card"><h4>Ежемесячный платёж</h4><p>{formatMoney(active.monthlyPayment ?? active.schedule[0]?.payment ?? 0)}</p></div><div className="card interest"><h4>Переплата банку</h4><p>{formatMoney(active.summary.totalInterest)}</p></div><div className="card"><h4>Полная стоимость кредита</h4><p>{formatMoney(active.summary.totalPayment)}</p></div><div className="card insurance-kpi"><h4>Страховки</h4><p>{formatMoney(active.summary.totalInsuranceCost)}</p></div><div className="card"><h4>Реальная стоимость</h4><p>{formatMoney(active.summary.totalRealCost)}</p></div><div className="card"><h4>Дата закрытия</h4><p>{active.summary.closingDate}</p></div></div></div>
    <div className="panel section income-panel"><h3>Рекомендуемый доход</h3><p>Для комфортной нагрузки желательно от <b>{formatMoney(recommendedIncomeComfort)}/мес.</b></p><p>Если доход около <b>{formatMoney(recommendedIncomeTense)}/мес.</b> — нагрузка уже напряжённая.</p><p>Если платёж больше 50% дохода — высокий риск перегруза.</p>{incomeRatio !== undefined ? <p className={`income-zone ${incomeZone}`}>Ваша доля ипотеки в доходе: <b>{Math.round(incomeRatio * 100)}%</b>, зона: <b>{incomeZone}</b>.</p> : null}<small className="muted-note">Это не банковское одобрение, а бытовой индикатор нагрузки. Учитывается платёж плюс средняя месячная стоимость страховок.</small></div>
    <div className="panel section effect-panel"><h3>Экономия от досрочек</h3>{hasPrepayments ? <><ul><li>Вы уже уменьшили будущую переплату на <strong>{formatMoney(result.interestSavings)}</strong>.</li><li>Это <strong>{savedApartmentEquivalent.toFixed(2)}</strong> стоимости квартиры.</li><li>Кредит стал короче на <strong>{result.monthsSaved} мес.</strong></li><li>Самый полезный платёж: <strong>{bestPayment ? `${bestPayment.date} · ${formatMoney(bestPayment.prepayment)}` : '—'}</strong></li></ul><div className="saving-bar"><span style={{ width: `${progress}%` }} /></div><div className="saving-scale"><span>было бы банку {formatMoney(result.baseline.summary.totalInterest)}</span><span>осталось банку {formatMoney(active.summary.totalInterest)}</span><span>уже сэкономлено {formatMoney(result.interestSavings)}</span></div></> : <p>Добавьте досрочные, чтобы увидеть экономию.</p>}</div>
    <div className="panel section"><h3>Что дала каждая досрочка</h3>{effects.length ? <div className="effect-list">{effects.map((effect) => <div key={effect.id} className="insight-card"><b>{effect.title}: {formatMoney(effect.amount)} {effect.count > 1 ? `× ${effect.count}` : ''}</b><span>{effect.date}, {modeLabel(effect.mode)}</span><span>Всего внесено: {formatMoney(effect.totalAmount)}</span><span>Экономия процентов: {formatMoney(effect.interestSavings)}</span><span>Сокращение срока: {durationText(effect.monthsSaved)}</span><small>{effect.count > 1 ? `Регулярная досрочка агрегирована: средняя экономия одного платежа ${formatMoney(effect.interestSavings / Math.max(1, effect.count))}.` : `Досрочный платёж от ${effect.date} сэкономил ${formatMoney(effect.interestSavings)} процентов.`}</small></div>)}</div> : <p>Нет активных досрочных платежей.</p>}</div>
    <div className="panel section"><h3>Центр 3. Что банк забирает на самом деле</h3><p>В первые 12 месяцев банку уйдёт <b>{formatMoney(firstYearInterest)}</b> процентов, а в тело долга — только <b>{formatMoney(firstYearPrincipal)}</b>.</p><p>До точки перелома вы в основном платите проценты: <b>{breakPoint?.date ?? 'не найдена'}</b>.</p><p>Из каждого 1 000 ₽ платежа примерно <b>{Math.round((bankShare / 100) * 1000)} ₽</b> уходит банку.</p><div className="real-cost-box"><h4>Сколько квартир вы реально оплатите</h4><p>При текущем графике квартира стоит не {formatMoney(input.propertyPrice)}, а <b>{formatMoney(active.summary.totalRealCost)}</b>.</p><p>Это как купить <b>{active.summary.realCostMultiplier.toFixed(2)}</b> такой квартиры.</p>{active.summary.totalInsuranceCost > 0 ? <p>С учётом страховок: <b>{active.summary.realCostMultiplier.toFixed(2)}</b> квартиры.</p> : null}<p>Проценты банку равны <b>{bankApartmentEquivalent.toFixed(2)}</b> стоимости этой квартиры.</p>{hasPrepayments ? <p>Досрочными платежами вы уже забрали у банка <b>{savedApartmentEquivalent.toFixed(2)}</b> стоимости квартиры. Такую сумму вы бы отдали банку процентами без досрочек.</p> : null}</div></div>
    <div className="panel section"><h3>Краткий автосценарий</h3><div className="quick-settings"><label><span>Доп. сумма</span><MoneyInput value={autoScenario.amount} onValueChange={(amount) => setAutoScenario({ ...autoScenario, amount })} /></label><label><span>Частота</span><select value={autoScenario.frequency} onChange={(e) => setAutoScenario({ ...autoScenario, frequency: e.target.value as AutoScenarioSettings['frequency'] })}><option value="monthly">каждый месяц</option><option value="semiAnnual">раз в 6 месяцев</option><option value="annual">раз в год</option></select></label><label><span>Режим</span><select value={autoScenario.mode} onChange={(e) => setAutoScenario({ ...autoScenario, mode: e.target.value as PrepaymentMode })}><option value="reduceTerm">уменьшать срок</option><option value="reducePayment">уменьшать платёж</option></select></label></div></div>
  </>;
}
